### ISSUE TITLE
微信和QQ支付好像仍存在问题

### ISSUE THREAD

**Issue by hans362** [tutugreen/WHMCS-JSJ-API-Pay-Gateway#4]
客户使用微信或QQ支付后，金沙江API后台可以看到付款记录，但是WHMCS里面的订单上仍显示未付款，网页没有任何反应，WHMCS后台也没有任何付款记录。

**Comment by tutugreen** [comment]
试试支付宝，付款完成后立即关闭页面，看看后台是否回调成功
接口日志是否有任何信息
站点是否使用CDN，是否有安全策略/WAF拦截可能
如站点启用HTTPS，站点后台，常规设置 - "WHMCS系统网址"是否设定设置为 "https://" 开头的唯一地址

请尝试检查上述内容，如仍无法解决请群内联系窝（12744）帮您远程看下。

**Comment by hans362** [comment]
谢谢，已经解决
