### ISSUE TITLE
在WHMCS的v7.4.2版本下,使用Alipay支付有小BUG.

### ISSUE THREAD

**Issue by Senrt** [tutugreen/WHMCS-JSJ-API-Pay-Gateway#6]
使用Alipay支付成功后,产品也开通了,结果发现刚刚支付的钱充进了余额.
例如这个产品是5美元的,使用Alipay支付,一切正常,就是事后多了5美元进了余额.

我不确定是不是我的问题还是v7.4.2问题还是其他.

**Comment by Senrt** [comment]
刚刚看了一下,应该是5美元转换到人民币32.19到支付宝支付.
然后返回的时候WHMCS认为多付了钱(32.19-5=27.19)
最终,多了27.19美元的余额.还没有找到解决方法..

**Comment by tutugreen** [comment]
惊了。。
我之后试下，如果有问题我再回复。

**Comment by Senrt** [comment]
如果你无法复现,我会尝试临时开一台机器再次复现.
当时网站以美元为主要货币,是通过WHMCS内部设置汇率转换到人民币再支付的.

**Comment by tutugreen** [comment]
确实有问题，在修正ing。

**Comment by tutugreen** [comment]
已修复，请尝试更新新版。

https://github.com/tutugreen/WHMCS-JSJ-API-Pay-Gateway/releases/tag/v0.17-2018-01-17-01

**Comment by Senrt** [comment]
不错哦,回去看看.
