### ISSUE TITLE
提示二维码获取失败, 请重试

### ISSUE THREAD

**Issue by tianji1993** [tutugreen/WHMCS-JSJ-API-Pay-Gateway#9]
错误信息:
http://prntscr.com/k0ajlp

在服务器上测试了到qpay.qq.com/qr的连通性, 结果正常.
有什么排查方法吗?

**Comment by tianji1993** [comment]
@tutugreen

**Comment by tutugreen** [comment]
可群内联系@12744远程看下。

PS：需要测试到https://yun.jsjapp.com/的连通性，和QQ没有关系。

**Comment by CQUTWangHong** [comment]
我现在用这个也报这个问题，获取二维码失败，请问大佬解决了吗

**Comment by tutugreen** [comment]
@CQUTWangHong 已重制新接口，请尝试新版本。
